/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rpg.frame;

import javax.swing.JOptionPane;
/**
 *
 * @author YufaAzera
 */
public class MenuUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUtama.class.getName());

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCharacter = new javax.swing.JButton();
        btnWeapon = new javax.swing.JButton();
        btnQuest = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RPG GAME DATABASE");
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(20, 30, 48));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 215, 0));
        jLabel1.setText("RPG GAME DATABASE");

        btnCharacter.setBackground(new java.awt.Color(55, 55, 55));
        btnCharacter.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCharacter.setForeground(new java.awt.Color(255, 255, 255));
        btnCharacter.setText("Character");
        btnCharacter.setFocusPainted(false);
        btnCharacter.setPreferredSize(new java.awt.Dimension(200, 30));
        btnCharacter.setRolloverEnabled(false);
        btnCharacter.addActionListener(this::btnCharacterActionPerformed);

        btnWeapon.setBackground(new java.awt.Color(55, 55, 55));
        btnWeapon.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnWeapon.setForeground(new java.awt.Color(255, 255, 255));
        btnWeapon.setText("Weapon");
        btnWeapon.setFocusPainted(false);
        btnWeapon.setPreferredSize(new java.awt.Dimension(200, 30));
        btnWeapon.addActionListener(this::btnWeaponActionPerformed);

        btnQuest.setBackground(new java.awt.Color(55, 55, 55));
        btnQuest.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnQuest.setForeground(new java.awt.Color(255, 255, 255));
        btnQuest.setText("Quest");
        btnQuest.setFocusPainted(false);
        btnQuest.setPreferredSize(new java.awt.Dimension(200, 30));
        btnQuest.addActionListener(this::btnQuestActionPerformed);

        btnExit.setBackground(new java.awt.Color(55, 55, 55));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.setFocusPainted(false);
        btnExit.setPreferredSize(new java.awt.Dimension(200, 30));
        btnExit.setRolloverEnabled(false);
        btnExit.addActionListener(this::btnExitActionPerformed);

        jSeparator1.setBackground(new java.awt.Color(255, 215, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 215, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnCharacter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCharacterActionPerformed


    TampilCharacter tampil = new TampilCharacter();

    tampil.setLocationRelativeTo(null);
    tampil.setVisible(true);

    dispose();

   // TODO add your handling code here:
    }//GEN-LAST:event_btnCharacterActionPerformed

    private void btnWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeaponActionPerformed

    try {

        TampilWeapon tampil = new TampilWeapon();
        tampil.setLocationRelativeTo(null);
        tampil.setVisible(true);

        dispose();

    } catch (Exception e) {

        e.printStackTrace();

        JOptionPane.showMessageDialog(this, e.toString());

    }


// TODO add your handling code here:
    }//GEN-LAST:event_btnWeaponActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    int pilih = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin keluar?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION
    );

    if (pilih == JOptionPane.YES_OPTION) {
        System.exit(0);
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnQuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuestActionPerformed

    TampilQuest tampil = new TampilQuest();

    tampil.setLocationRelativeTo(null);

    tampil.setVisible(true);

    dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(() -> {
        new MenuUtama().setVisible(true);
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCharacter;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnQuest;
    private javax.swing.JButton btnWeapon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

   
}
