/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rpg.frame;
import com.rpg.database.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author YufaAzera
 */
public class TampilWeapon extends javax.swing.JFrame {
    private int idTerpilih = -1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TampilWeapon.class.getName());

    /**
     * Creates new form TampilWeapon
     */
    public TampilWeapon() {

    initComponents();
    tampilData();
    setLocationRelativeTo(null);

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        tblWeapon = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnTambahWeapon = new javax.swing.JButton();
        btnRefreshWeapon = new javax.swing.JButton();
        btnHapusWeapon = new javax.swing.JButton();
        btnKembaliWeapon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("TampilCharacter");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 30, 48));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        tblWeapon.setViewportView(jTable1);

        btnTambahWeapon.setBackground(new java.awt.Color(55, 55, 55));
        btnTambahWeapon.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahWeapon.setText("Tambah");
        btnTambahWeapon.setPreferredSize(new java.awt.Dimension(100, 30));
        btnTambahWeapon.addActionListener(this::btnTambahWeaponActionPerformed);

        btnRefreshWeapon.setBackground(new java.awt.Color(55, 55, 55));
        btnRefreshWeapon.setForeground(new java.awt.Color(255, 255, 255));
        btnRefreshWeapon.setText("Refresh");
        btnRefreshWeapon.setPreferredSize(new java.awt.Dimension(100, 30));
        btnRefreshWeapon.addActionListener(this::btnRefreshWeaponActionPerformed);

        btnHapusWeapon.setBackground(new java.awt.Color(55, 55, 55));
        btnHapusWeapon.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusWeapon.setText("Hapus");
        btnHapusWeapon.setPreferredSize(new java.awt.Dimension(100, 30));
        btnHapusWeapon.addActionListener(this::btnHapusWeaponActionPerformed);

        btnKembaliWeapon.setBackground(new java.awt.Color(55, 55, 55));
        btnKembaliWeapon.setForeground(new java.awt.Color(255, 255, 255));
        btnKembaliWeapon.setText("Kembali");
        btnKembaliWeapon.setPreferredSize(new java.awt.Dimension(100, 30));
        btnKembaliWeapon.addActionListener(this::btnKembaliWeaponActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 215, 0));
        jLabel1.setText("WEAPON");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tblWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambahWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnRefreshWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnHapusWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnKembaliWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tblWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembaliWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    int baris = jTable1.getSelectedRow();

    idTerpilih = Integer.parseInt(
            jTable1.getValueAt(baris, 0).toString());

        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnTambahWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahWeaponActionPerformed


    new TambahWeapon().setVisible(true);

    TambahWeapon tw = new TambahWeapon();
    tw.setLocationRelativeTo(null);
    tw.setVisible(true);

    dispose();


    dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahWeaponActionPerformed

    private void btnRefreshWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshWeaponActionPerformed

    tampilData();

// TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshWeaponActionPerformed

    private void btnHapusWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusWeaponActionPerformed


    if (idTerpilih == -1) {

        JOptionPane.showMessageDialog(this,
                "Pilih data terlebih dahulu.");
        return;

    }

    int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus weapon ini?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION
    );

    if (konfirmasi == JOptionPane.YES_OPTION) {

        try {

            Connection conn = Koneksi.getKoneksi();

            String sql = "DELETE FROM weapon WHERE id=?";

            PreparedStatement pst = conn.prepareStatement(sql);

            pst.setInt(1, idTerpilih);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Weapon berhasil dihapus.");

            idTerpilih = -1;

            tampilData();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());

        }

    }

// TODO add your handling code here:
    }//GEN-LAST:event_btnHapusWeaponActionPerformed

    private void btnKembaliWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliWeaponActionPerformed


    MenuUtama menu = new MenuUtama();
    menu.setLocationRelativeTo(null);
    menu.setVisible(true);

    dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliWeaponActionPerformed
public void tampilData() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nama Weapon");
    model.addColumn("Tipe Weapon");
    model.addColumn("Attack");

    try {

        Connection conn = Koneksi.getKoneksi();

        String sql = "SELECT * FROM weapon";

        PreparedStatement pst = conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{

                rs.getInt("id"),
                rs.getString("nama_weapon"),
                rs.getString("tipe_weapon"),
                rs.getInt("attack")

            });

        }

        jTable1.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());

    }

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TampilWeapon().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusWeapon;
    private javax.swing.JButton btnKembaliWeapon;
    private javax.swing.JButton btnRefreshWeapon;
    private javax.swing.JButton btnTambahWeapon;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tblWeapon;
    // End of variables declaration//GEN-END:variables

}
