/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rpg.frame;

import com.rpg.database.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author YufaAzera
 */
public class TampilQuest extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TampilQuest.class.getName());

    /**
     * Creates new form TampilQuest
     */
    public TampilQuest() {
    initComponents();
    tampilData();
    setLocationRelativeTo(null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tblQuest = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnTambahQuest = new javax.swing.JButton();
        btnRefreshQuest = new javax.swing.JButton();
        btnHapusQuest = new javax.swing.JButton();
        btnKembaliQuest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 30, 48));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        tblQuest.setViewportView(jTable1);

        btnTambahQuest.setBackground(new java.awt.Color(55, 55, 55));
        btnTambahQuest.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahQuest.setText("Tambah");
        btnTambahQuest.setPreferredSize(new java.awt.Dimension(100, 30));
        btnTambahQuest.addActionListener(this::btnTambahQuestActionPerformed);

        btnRefreshQuest.setBackground(new java.awt.Color(55, 55, 55));
        btnRefreshQuest.setForeground(new java.awt.Color(255, 255, 255));
        btnRefreshQuest.setText("Refresh");
        btnRefreshQuest.setPreferredSize(new java.awt.Dimension(100, 30));
        btnRefreshQuest.addActionListener(this::btnRefreshQuestActionPerformed);

        btnHapusQuest.setBackground(new java.awt.Color(55, 55, 55));
        btnHapusQuest.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusQuest.setText("Hapus");
        btnHapusQuest.setPreferredSize(new java.awt.Dimension(100, 30));
        btnHapusQuest.addActionListener(this::btnHapusQuestActionPerformed);

        btnKembaliQuest.setBackground(new java.awt.Color(55, 55, 55));
        btnKembaliQuest.setForeground(new java.awt.Color(255, 255, 255));
        btnKembaliQuest.setText("Kembali");
        btnKembaliQuest.setPreferredSize(new java.awt.Dimension(100, 30));
        btnKembaliQuest.addActionListener(this::btnKembaliQuestActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 215, 0));
        jLabel1.setText("QUEST");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tblQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTambahQuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnRefreshQuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnHapusQuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnKembaliQuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tblQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahQuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshQuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusQuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembaliQuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahQuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahQuestActionPerformed

    TambahQuest tq = new TambahQuest();

    tq.setLocationRelativeTo(null);
    tq.setVisible(true);

    dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahQuestActionPerformed

    private void btnRefreshQuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshQuestActionPerformed

    tampilData();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshQuestActionPerformed

    private void btnKembaliQuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliQuestActionPerformed

    MenuUtama menu = new MenuUtama();

    menu.setVisible(true);

    dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnKembaliQuestActionPerformed
    private int idTerpilih = -1;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    int baris = jTable1.getSelectedRow();

    idTerpilih = Integer.parseInt(
            jTable1.getValueAt(baris,0).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnHapusQuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusQuestActionPerformed

    if(idTerpilih==-1){

        JOptionPane.showMessageDialog(this,
                "Pilih data terlebih dahulu.");

        return;

    }

    int pilih = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus quest?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

    if(pilih==JOptionPane.YES_OPTION){

        try{

            Connection conn = Koneksi.getKoneksi();

            String sql="DELETE FROM quest WHERE id=?";

            PreparedStatement pst=conn.prepareStatement(sql);

            pst.setInt(1,idTerpilih);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Quest berhasil dihapus.");

            tampilData();

            idTerpilih=-1;

        }catch(Exception e){

            JOptionPane.showMessageDialog(this,
                    e.getMessage());

        }

    }
       // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusQuestActionPerformed
public void tampilData() {

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID");
    model.addColumn("Nama Quest");
    model.addColumn("Grade");
    model.addColumn("Reward");

    try {

        Connection conn = Koneksi.getKoneksi();

        String sql = "SELECT * FROM quest";

        PreparedStatement pst = conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{

                rs.getInt("id"),
                rs.getString("nama_quest"),
                rs.getString("grade"),
                rs.getString("reward")

            });

        }

        jTable1.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                e.getMessage());

    }

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TampilQuest().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusQuest;
    private javax.swing.JButton btnKembaliQuest;
    private javax.swing.JButton btnRefreshQuest;
    private javax.swing.JButton btnTambahQuest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tblQuest;
    // End of variables declaration//GEN-END:variables
}
